spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chieh?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.web: trace
